### ISSUE TITLE
Error: Result 1 is not a length 1 atomic vector

### ISSUE THREAD

**Issue by henry090** [andrie/deepviz#2]
vocab_size <- 15000

model <- keras_model_sequential() %>% 
  layer_embedding(input_dim = vocab_size, output_dim = 16) %>%
  layer_global_average_pooling_1d() %>%
  layer_dense(units = 16, activation = "relu",
              kernel_regularizer = regularizer_l2(l=0.1)) %>%
  layer_gaussian_dropout(rate = 0.2) %>% 
  layer_dense(units = 1, activation = "sigmoid",kernel_regularizer = regularizer_l2(l=0.004)) 
model %>% deepviz::plot_model()
Error: Result 1 is not a length 1 atomic vector

**Comment by skeydan** [comment]
![image](https://user-images.githubusercontent.com/469371/46693483-2c504f00-cc0a-11e8-905b-c75acc66c850.png)

**Comment by henry090** [comment]
@skeydan Could you make it bigger (for quality)?

**Comment by henry090** [comment]
@andrie this package has lots of dependencies, unfortunately, I got errors about 5 times, like: 'some package does not exist' --> error. So I was obliged to install them manually... Why do I get an error?

**Comment by andrie** [comment]
@henry090 , please open a new issue and provide as much information as you can about the failures.

**Comment by andrie** [comment]
Also, I can't reproduce the original error you report.  As @skeydan reports, the code works and creates the plot that she posted.

**Comment by henry090** [comment]
Closing issue? Instead of closing you could write something clear. I pasted what I got while executing a code snippet!
