### ISSUE TITLE
Any way to install for R 3.4.x?

### ISSUE THREAD

**Issue by nateGeorge** [andrie/deepviz#9]
This looks like a great package, but I'd like to install it with R 3.4 versions.  Is there any way to do that?

**Comment by nateGeorge** [comment]
Well, I just cloned it and it seems to work with 3.4 if the line in DESCRIPTION is changed to allow version 3.4.  Not sure if anything is broken, but the examples seem to work fine: https://andrie.github.io/deepviz/index.html

**Comment by andrie** [comment]
Interesting.   I can't remember why this was marked as `R (>= 3.5)` or whether this is an incidental artefact.  I'm glad it's working for you, though.

**Comment by nateGeorge** [comment]
Hmm, well I guess everyone should be moving to higher R versions anyway.  On Ubuntu it wasn't trivial to install 3.5 vs 3.4 for me, so I'd definitely prefer everything to stay 3.4 for now.  Oh well.
